name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image and push to repo
      run: docker build . --file Dockerfile/Dockerfile --tag spacy:$(date +%s)
      run: docker push mauromussin/spacy:$(date +%s)
